app:
  name: customers
  namespace: customers-user1
  cluster: {{ gitea_customize_apps_subdomain }}

git:
  branch: master
  repo: https://{{ gitea_customize_gitea_endpoint }}/gitea/{{ gitea_customize_lab_username }}-pipeline-gitops.git
  org: development
  name: pipeline-gitops
  host: {{ gitea_customize_gitea_endpoint }}
  token: ''
  webhookSecret: ''
  verify_commits: disabled

lab:
  username: {{ gitea_customize_lab_username }}

image:
  registry: Quay
  organization: quayadmin
  host: {{ gitea_customize_quay_server }}
  name: customers
  tag: v1
