app:
  name: customers
  namespace: customers-user1
  cluster: {{ gitea_customize_apps_subdomain }}

git:
  branch: master
  repo: {{ gitea_customize_gitea_server }}/{{ gitea_customize_lab_username }}/my-quarkus-app4.git
  org: development
  name: pipeline-gitops
  host: {{ gitea_customize_gitea_server }}
  token: ''
  webhookSecret: ''
  verify_commits: disabled

lab:
  username: {{ gitea_customize_lab_username }}

image:
  registry: Quay
  organization: quayadmin
  host: {{ gitea_customize_quay_server }}
  name: customers
  tag: v1
