app:
  name: customers
  namespace: customers-user1
  cluster: .apps.cluster-4jb4z.4jb4z.sandbox1586.opentlc.com

git:
  branch: master
  repo: https://gitlab-gitlab.apps.cluster-4jb4z.4jb4z.sandbox1586.opentlc.com/development/my-quarkus-app4.git
  org: development
  name: my-quarkus-app4
  host: gitlab-gitlab.apps.cluster-4jb4z.4jb4z.sandbox1586.opentlc.com
  token: ''
  webhookSecret: ''
  verify_commits: disabled


image:
  registry: Quay
  organization: quayadmin
  host: quay-4jb4z.apps.cluster-4jb4z.4jb4z.sandbox1586.opentlc.com
  name: customers
  tag: v1
